import {StackNavigationProp} from '@react-navigation/stack';

export type RootStackParamList = {
    WelcomeScreen: undefined;
    TransitionScreen1: undefined;
    TransitionScreen2: undefined;
    TransitionScreen3: undefined;
    TransitionScreen4: undefined;
    TransitionScreen5: undefined;
    NameScreen: undefined;
    AgeScreen: { userData: UserData };  
    GenderScreen: { userData: UserData };
    QuranConnectionScreen: { userData: UserData };
    QuizScreen6: { userData: UserData };
    QuizScreen7: { userData: UserData };
    QuizScreen8: { userData: UserData };
    QuizScreen9: { userData: UserData };    
    QuizScreen10: { userData: UserData };
    QuizScreen11: { userData: UserData };
    QuizScreen12: { userData: UserData };
    QuizScreen13: { userData: UserData };
    QuizScreen14: { userData: UserData };
    JoinThousandsScreen: undefined;
    CostExplanationScreen: undefined;
    JourneyScreen: undefined;
    DiscountScreen: undefined;
    ChatApp: undefined;
    SettingsScreen: undefined;
    ProfileInformationScreen: undefined;
    ChangePasswordScreen: undefined;
    SubscriptionManagementScreen: undefined;
    VoiceToTextSettingsScreen: undefined;
    AIResponseLengthScreen: undefined;
    FAQsScreen: undefined;
    ManageDevicesScreen: undefined;
    ClearHistoryScreen: undefined;
    ReportProblemScreen: undefined;
    DownloadDataScreen: undefined;
    CreatePinScreen: undefined;
    AppLockMainScreen: { appLockEnabled: boolean } | undefined;
    PinSuccessScreen: {pin: string} | undefined;
    Awareness1Screen: undefined;
    Awareness2Screen: undefined;
    Awareness3Screen: undefined;
    Awareness4Screen: undefined;
    Awareness5Screen: undefined;
    Awareness6Screen: undefined;
    ChatWelcomeScreen: undefined;
    ChatScreen: undefined;
};
export type NavigationProp = StackNavigationProp<RootStackParamList>;